sudo: required
services: 
  - docker 

before_install:
  - docker build -t iviberberi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true iviberberi/react-test npm test -- --coverage

after_success:
  - docker build -t iviberberidock/multi-client ./client
  - docker build -t iviberberidock/multi-nginx ./nginx
  - docker build -t iviberberidock/multi-server ./server
  - docker build -t iviberberidock/multi-worker ./worker

  #Log in to docker hub 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take images and push to docker hub
  - docker push iviberberidock/multi-client
  - docker push iviberberidock/multi-nginx
  - docker push iviberberidock/multi-server
  - docker push iviberberidock/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-247221886776
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
